package com.team.telstra.console.ruledef;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class PrefundingFinanceInputDO implements java.io.Serializable {

	static final long serialVersionUID = 1L;

	@org.kie.api.definition.type.Label(value = "Project Type")
	private java.lang.String projectType;
	@org.kie.api.definition.type.Label(value = "Project sub type")
	private java.lang.String projectSubType;
	@org.kie.api.definition.type.Label(value = "Region")
	private java.lang.String region;
	@org.kie.api.definition.type.Label(value = "Funding type")
	private java.lang.String fundingType;

	public PrefundingFinanceInputDO() {
	}

	public java.lang.String getProjectType() {
		return this.projectType;
	}

	public void setProjectType(java.lang.String projectType) {
		this.projectType = projectType;
	}

	public java.lang.String getProjectSubType() {
		return this.projectSubType;
	}

	public void setProjectSubType(java.lang.String projectSubType) {
		this.projectSubType = projectSubType;
	}

	public java.lang.String getRegion() {
		return this.region;
	}

	public void setRegion(java.lang.String region) {
		this.region = region;
	}

	public java.lang.String getFundingType() {
		return this.fundingType;
	}

	public void setFundingType(java.lang.String fundingType) {
		this.fundingType = fundingType;
	}

	public PrefundingFinanceInputDO(java.lang.String projectType,
			java.lang.String projectSubType, java.lang.String region,
			java.lang.String fundingType) {
		this.projectType = projectType;
		this.projectSubType = projectSubType;
		this.region = region;
		this.fundingType = fundingType;
	}

}